Hotfix/lst 1328 GitHub vulnerability scan
uktrade/data-hub-helpcentre pull request #62
Opened 2021-04-21 15:24 UTC by Luisella21

Several changes due to security alert.
Important: the sql script must be executed before the migrations.

2021-04-21 16:55 UTC, rossmiller requested changes
Looks very good! Some changes needed to logging (which is my fault for not explaining more).

2021-04-21 16:55 UTC, rossmiller commented on config/settings/base.py
> +LOGGING = {
We need to change or remove this logging config.

2021-04-21 16:55 UTC, rossmiller commented on config/settings/env.py
> +            "stream": sys.stdout,  # noqa F405
Could you please remove lines 29 and 34?

2021-04-22 07:28 UTC, Luisella21 commented on config/settings/base.py
> +LOGGING = {
I removed it.

2021-04-22 07:29 UTC, Luisella21 commented on config/settings/env.py
> +            "stream": sys.stdout,  # noqa F405
Done.

2021-04-23 14:27 UTC, rossmiller approved these changes
LGTM!

2021-04-23 14:28 UTC, merged